# Generated by Django 5.0.1 on 2024-03-27 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_title', models.CharField(max_length=200)),
                ('date_release', models.DateTimeField(verbose_name='date release')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ep_title', models.CharField(max_length=200)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaapp.show')),
            ],
        ),
    ]
