# Generated by Django 5.0.1 on 2024-03-27 19:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='date_release',
            new_name='show_date',
        ),
        migrations.AddField(
            model_name='episode',
            name='ep_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date release'),
            preserve_default=False,
        ),
    ]
