# Generated by Django 5.0.1 on 2024-03-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaapp', '0002_rename_date_release_show_show_date_episode_ep_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='ep_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='episode',
            name='ep_season',
            field=models.IntegerField(default=0),
        ),
    ]
